test_secrets: Use python-psutil instead of checking /proc
Patch check only leaks in opened unix sockets but it improves a little
bit error reporting.

iTraceback (most recent call last):
  File "src/tests/intg/test_secrets.py", line 410, in test_idle_timeout
    assert fds_pre == fds_post, \
AssertionError: FD difference
  set()
  {pconn(fd=11, family=<AddressFamily.AF_UNIX: 1>, type=1,
         laddr='/tmp/sssd-intg.3gb4hzpn/var/run/secrets.socket',
         raddr=None, status='NONE')}